name: Update dependencies

on:
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:

jobs:
  update-dependencies:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        # It's necessary to fetch with other token otherwise the push doesn't trigger other Github Action workflows
        # https://github.com/orgs/community/discussions/37103
        token: ${{ secrets.PAT }}
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'

    - run: npm ci

    - run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "hello@moleculer.services"
        git checkout -b update-deps-$GITHUB_RUN_ID

    - run: npm run ci-update-deps
    - run: npm i
    - run: npm audit fix || true

    - run: |
        git commit -am "Update dependencies (auto)"
        git push origin update-deps-$GITHUB_RUN_ID
    - run: |
        gh pr create --title "[deps]: Update all dependencies" --body ""
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
